version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: taskmanager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: taskManager
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    image: docker.io/sergiomontero97/taskmanager_backend:latest
    container_name: taskmanager_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskManager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: docker.io/sergiomontero97/taskmanager_frontend:latest
    container_name: taskmanager_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
