-- Inserción de registros iniciales en la tabla `task`
INSERT INTO tasks (completed, description, title, priority) VALUES
(1, 'Actualizar la documentacion del proyecto.', 'Actualizar documentacion', NULL),
(1, 'Preparar la presentacion para la reunion de equipo.', 'Preparar presentacion', NULL),
(1, 'Realizar copia de seguridad de la base de datos.', 'Backup de base de datos', NULL),
(1, 'Optimizar las consultas SQL en el sistema.', 'Optimizacion SQL', NULL),
(1, 'Hacer pruebas unitarias en el modulo de usuarios.', 'Pruebas unitarias', NULL),
(1, 'Enviar informe de progreso al gerente.', 'Enviar informe', NULL),
(1, 'Actualizar el estado de los tickets en el sistema.', 'Actualizar tickets', NULL),
(1, 'Completar la migracion del sistema a la nueva version.', 'Migracion del sistema', NULL),
(1, 'Revisar y aprobar solicitudes de acceso.', 'Revision de accesos', NULL),
(1, 'Actualizar scripts de despliegue.', 'Actualizar scripts', NULL),
(1, 'Implementar el sistema de notificaciones.', 'Sistema de notificaciones', NULL),
(1, 'Optimizar consultas en el modulo de facturacion.', 'Optimizar facturacion', NULL),
(1, 'Corregir errores en el modulo de inventario.', 'Correccion de inventario', NULL),
(1, 'Configurar balanceador de carga.', 'Configurar balanceador', NULL),
(1, 'Actualizar certificados SSL.', 'Actualizar SSL', NULL),
(1, 'Revisar rendimiento del servidor de produccion.', 'Rendimiento servidor', NULL),
(1, 'Revisar y aprobar cambios de codigo.', 'Revision de codigo', NULL),
(1, 'Actualizar dependencias del proyecto.', 'Actualizar dependencias', NULL),
(1, 'Documentar nuevos endpoints de la API.', 'Documentar endpoints', NULL),
(1, 'Refactorizar el modulo de pagos.', 'Refactorizar pagos', NULL),
(1, 'Corregir errores en el modulo de autenticacion.', 'Errores de autenticacion', NULL),
(1, 'Asegurar endpoints criticos con rate-limiting.', 'Rate-limiting', NULL),
(1, 'Mejorar rendimiento del dashboard.', 'Rendimiento dashboard', NULL),
(1, 'Implementar encriptacion de datos sensibles.', 'Encriptacion datos', NULL),
(1, 'Actualizar el diseno del formulario de registro.', 'Diseno formulario', NULL),
(1, 'Corregir errores visuales en la interfaz.', 'Errores visuales UI', NULL),
(1, 'Documentar decisiones tecnicas recientes.', 'Documentar decisiones', NULL),
(1, 'Corregir inconsistencias en datos de produccion.', 'Inconsistencias datos', NULL),
(1, 'Implementar mejoras en el sistema de reportes.', 'Mejoras en reportes', NULL),
(1, 'Revisar alertas de seguridad criticas.', 'Alertas de seguridad', NULL),
(1, 'Investigar nuevas tecnologias para frontend.', 'Tecnologias frontend', NULL),
(1, 'Corregir errores en el despliegue continuo.', 'Errores despliegue', NULL),
(0, 'Configurar nuevo servidor de desarrollo.', 'Configurar servidor', 1),
(0, 'Escribir documentacion para la API REST.', 'Documentar API', 2),
(0, 'Investigar nuevas tecnologias para optimizacion.', 'Investigacion de tecnologias', 3),
(0, 'Redisear la interfaz de usuario del dashboard.', 'Rediseo UI', 4),
(0, 'Revisar errores reportados por usuarios.', 'Correccion de errores', 5),
(0, 'Crear nuevos casos de prueba para el modulo de autenticacion.', 'Casos de prueba', 6),
(0, 'Optimizar la carga de imagenes en la aplicacion.', 'Optimizar imagenes', 7),
(0, 'Configurar alertas automaticas en el sistema.', 'Configurar alertas', 8),
(0, 'Implementar autenticacion de dos factores.', 'Autenticacion 2FA', 9),
(0, 'Configurar pipeline de integracion continua.', 'Configurar CI', 10),
(0, 'Redactar politicas de seguridad de datos.', 'Politicas de seguridad', 11),
(0, 'Realizar analisis de logs del sistema.', 'Analisis de logs', 12),
(0, 'Probar compatibilidad en navegadores moviles.', 'Pruebas en moviles', 13),
(0, 'Implementar cacheo en endpoints REST.', 'Cacheo REST', 14),
(0, 'Agregar soporte multilenguaje en la app.', 'Soporte multilenguaje', 15),
(0, 'Crear sistema de gestion de logs centralizados.', 'Gestion de logs', 16),
(0, 'Automatizar pruebas de regresion.', 'Automatizar pruebas', 17),
(0, 'Configurar monitoreo de trafico.', 'Monitoreo de trafico', 18),
(0, 'Optimizar el algoritmo de busqueda.', 'Optimizar busqueda', 19),
(0, 'Disenar nuevas plantillas de correos.', 'Diseno de plantillas', 20),
(0, 'Probar integraciones con proveedores externos.', 'Pruebas integraciones', 21),
(0, 'Agregar logging detallado a los procesos criticos.', 'Logging detallado', 22),
(0, 'Actualizar y estandarizar mensajes de error.', 'Mensajes de error', 23),
(0, 'Definir metricas clave para monitoreo.', 'Definir metricas', 24),
(0, 'Realizar auditoria de seguridad del sistema.', 'Auditoria de seguridad', 25),
(0, 'Configurar backups automaticos diarios.', 'Backups diarios', 26),
(0, 'Mejorar tiempos de carga inicial de la app.', 'Mejorar tiempos de carga', 27),
(0, 'Agregar control de versiones para assets.', 'Control de versiones', 28),
(0, 'Hacer pruebas de carga en el sistema.', 'Pruebas de carga', 29),
(0, 'Estudiar opciones de escalabilidad.', 'Opciones de escalabilidad', 30),
(0, 'Actualizar herramientas de desarrollo.', 'Actualizar herramientas', 31),
(0, 'Configurar dashboards en herramientas de monitoreo.', 'Configurar dashboards', 32),
(0, 'Optimizar flujos en la UX.', 'Optimizar UX', 33);
