-- Insertar usuarios
INSERT INTO users (auth0id, email, role) VALUES
('auth0|user1', 'user1@example.com', 'admin'),
('auth0|user2', 'user2@example.com', 'user'),
('auth0|user3', 'user3@example.com', 'user'),
('auth0|user4', 'user4@example.com', 'user'),
('auth0|user5', 'user5@example.com', 'user');

-- Insertar tareas
INSERT INTO tasks (completed, description, priority, title, user_id) VALUES
-- Tareas completadas
(1, 'Revisar reportes financieros', NULL, 'Análisis Financiero', 1),
(1, 'Actualizar documentación interna', NULL, 'Documentación', 2),
(1, 'Revisión de código en PRs', NULL, 'Code Review', 3),
(1, 'Realizar auditoría de seguridad', NULL, 'Auditoría Seguridad', 4),
(1, 'Actualizar servidores', NULL, 'Mantenimiento Servidor', 5),
(1, 'Capacitar equipo de ventas', NULL, 'Capacitación', 1),
(1, 'Preparar presentación de resultados', NULL, 'Presentación', 2),
(1, 'Optimización de scripts SQL', NULL, 'Optimización SQL', 3),
(1, 'Diseñar nueva landing page', NULL, 'Diseño Web', 4),
(1, 'Análisis de tendencias de mercado', NULL, 'Análisis de Mercado', 5),
(1, 'Actualizar configuración de red', NULL, 'Configuración Red', 1),
(1, 'Revisión de accesos y permisos', NULL, 'Control de Accesos', 2),
(1, 'Migrar servicios a la nube', NULL, 'Migración Cloud', 3),
(1, 'Implementación de API REST', NULL, 'Desarrollo API', 4),
(1, 'Revisión legal de contratos', NULL, 'Revisión Legal', 5),
(1, 'Revisión de código para auditoría', NULL, 'Auditoría Código', 1),
(1, 'Actualizar manual de usuario', NULL, 'Manual Usuario', 2),
(1, 'Corrección de bugs críticos', NULL, 'Corrección Bugs', 3),
(1, 'Revisión de documentación técnica', NULL, 'Doc Técnica', 4),
(1, 'Implementación de estrategias SEO', NULL, 'SEO Estrategias', 5),

-- Tareas pendientes con prioridad
(0, 'Redactar informe de ventas', 1, 'Informe de Ventas', 1),
(0, 'Optimizar base de datos', 2, 'Optimización DB', 1),
(0, 'Diseñar nueva interfaz de usuario', 3, 'Diseño UI', 2),
(0, 'Realizar pruebas de integración', 1, 'Pruebas QA', 2),
(0, 'Configurar servidor de staging', 2, 'Setup Staging', 3),
(0, 'Generar documentación técnica', 1, 'Documentación Técnica', 4),
(0, 'Revisión de diseño UX', 3, 'UX Review', 5),
(0, 'Implementar autenticación en la app', 2, 'Autenticación', 1),
(0, 'Configurar pipelines de CI/CD', 3, 'CI/CD Config', 2),
(0, 'Crear reportes automatizados', 1, 'Reportes Automatizados', 3),
(0, 'Pruebas de carga en servidores', 2, 'Load Testing', 4),
(0, 'Definir estrategia de marketing', 3, 'Estrategia Marketing', 5),
(0, 'Integración con proveedores externos', 1, 'Integración Proveedores', 1),
(0, 'Configurar dashboard de monitoreo', 2, 'Dashboard Monitoreo', 2),
(0, 'Implementar chatbot de soporte', 3, 'Chatbot Soporte', 3),
(0, 'Optimizar flujo de trabajo en equipo', 1, 'Optimización Workflows', 4),
(0, 'Desarrollar módulo de analítica', 2, 'Analítica Módulo', 5),
(0, 'Revisión de costos operativos', 3, 'Costos Operativos', 1),
(0, 'Actualizar políticas de seguridad', 1, 'Políticas Seguridad', 2),
(0, 'Investigación de nuevas tecnologías', 2, 'Investigación Tech', 3),
(0, 'Automatizar procesos de validación', 3, 'Automatización Validaciones', 4),
(0, 'Evaluar herramientas de monitoreo', 1, 'Herramientas Monitoreo', 5),
(0, 'Capacitación interna de empleados', 2, 'Capacitación Interna', 1),
(0, 'Desarrollar estrategia de fidelización', 3, 'Estrategia Fidelización', 2),
(0, 'Análisis de métricas de engagement', 1, 'Métricas Engagement', 3),
(0, 'Monitoreo y mantenimiento de servidores', 2, 'Mantenimiento Servidores', 4),
(0, 'Investigación de tendencias en UX/UI', 3, 'Investigación UX/UI', 5),
(0, 'Implementación de pruebas A/B', 1, 'Pruebas A/B', 1),
(0, 'Optimización de rendimiento en frontend', 2, 'Optimización Frontend', 2),
(0, 'Migración de datos a nueva plataforma', 3, 'Migración Datos', 3),
(0, 'Diseño de material de marketing', 1, 'Material Marketing', 4),
(0, 'Análisis de feedback de clientes', 2, 'Análisis Feedback', 5),
(0, 'Automatización de procesos internos', 3, 'Automatización Procesos', 1),
(0, 'Desarrollo de feature de notificaciones', 1, 'Notificaciones', 2),
(0, 'Optimización de queries en base de datos', 2, 'Optimización Queries', 3),
(0, 'Análisis de patrones de uso', 3, 'Patrones de Uso', 4),
(0, 'Monitoreo de logs y errores', 1, 'Monitoreo Logs', 5),
(0, 'Implementar cache en API', 2, 'Cache API', 1),
(0, 'Crear dashboard de administración', 3, 'Dashboard Admin', 2),
(0, 'Auditoría de accesos en sistemas', 1, 'Auditoría Accesos', 3),
(0, 'Monitoreo de tráfico web', 2, 'Tráfico Web', 4),
(0, 'Mejorar experiencia de onboarding', 3, 'Onboarding UX', 5),
(0, 'Evaluación de herramientas de análisis', 1, 'Evaluación Analytics', 1),
(0, 'Diseño de arquitectura de microservicios', 2, 'Arquitectura Microservicios', 2),
(0, 'Implementación de WebSockets', 3, 'WebSockets', 3),
(0, 'Revisión y optimización de logs', 1, 'Optimización Logs', 4),
(0, 'Definir procesos de recuperación ante fallos', 2, 'Recuperación Fallos', 5),
(0, 'Implementación de pruebas unitarias', 3, 'Pruebas Unitarias', 1);
